examples/control.rs
src/device.rs
src/platform/linux_usbfs/device.rs
src/platform/linux_usbfs/transfer.rs

Important for some use cases, but I'm not going to go as far as libusb to support this on WIndows -- libusb will temporarily claim a random interface just to submit a control transfer that is not necessarily related to that interface. So this is Linux-only, and portable code will need to use the `Interface` method. Should be supportable on macOS as well.

Allow control transfers on Linux without claiming interface

---

src/transfer/internal.rs

This seems wrong, unless it's intentional for some reason?

linux: Fix STATE_ABANDONED value

---

src/enumeration.rs
src/platform/macos_iokit/device.rs
src/platform/macos_iokit/enumeration.rs

It changes when the device is disconnected and reconnected, while the location ID is like a port number.
This prevents opening the wrong device if you hold onto a `DeviceInfo` for a while and a different device is connected to the same port.

macos: Use registry entry ID instead of location ID to identify device.

---

Cargo.toml

Hi, this an interesting library!
I noticed `futures-lite` is only used in `examples/` and (non-running) documentation tests. This change moves that dependency to `dev-dependencies` from `dependencies` since it's not used by the library itself. This means it's not added to the dependency tree of the `nusb`'s users.

Move futures-lite to dev-dependencies

---

src/platform/macos_iokit/events.rs

Note that I have no idea what I am doing, but was hunting for static state, and found this.
It seems to address what I saw in #18, but should definitely be sanity checked.
It seems that it is possible for the worker thread to exit (likely because there are no devices
still attached), but for the static to *appear* to still be working, so when we go back to
having devices, there is no event loop to service them.
This PR resets the static to the initial state when the worker thread terminates.
Closes #18

MacOS: Reset the static eventloop if the worker thread terminates

---

src/enumeration.rs
src/platform/linux_usbfs/enumeration.rs

Currently you can get a SysfsPath from DeviceInfo, but you can't really do anything
with it because it has no methods and the inner PathBuf is private.
This makes it pub.
The SysfsPath type is a bit useless from outside the crate though. Alternatvely DeviceInfo.path() could return a PathBuf,  but that's a breaking change.

Make SysfsPath contents pub.

---

src/platform/windows_winusb/enumeration.rs

DEVPKEY_Device_BusReportedDeviceDesc does return the actual product string
returned by the USB device.
It seems there's no property for the manufacturer string though :( 
I've confirmed by USB sniffing that this does no actual USB I/O.
related to #24

windows: return correct product string.

---

src/enumeration.rs
src/platform/windows_winusb/enumeration.rs

This comes from the INF used to install the driver, not the descriptor.
Related: https://github.com/kevinmehall/nusb/issues/24

windows: Stop returning manufacturer string

---

examples/detach_claim.rs
src/device.rs
src/platform/linux_usbfs/device.rs
src/platform/linux_usbfs/usbfs.rs
src/platform/macos_iokit/device.rs
src/platform/windows_winusb/device.rs

Closes #34 
Interestingly, the PR needs the fallback-to-racy code, otherwise it's not working on my ubuntu which is definitely not 12 years old (I'm getting "this ioctl is not valid for this device" error). Not sure what's going on there, maybe it's an undiscovered bug in libusb which I used as the source to port this code from. Or maybe I just can't copy code very well, as the number of force pushes here indicates :)

Implement `detach_and_claim_interface`

---

src/platform/macos_iokit/enumeration.rs

Use `kUSBHostInterfacePropertyString` (i.e. `"kUSBString"`) as the key when resolving the `interface_string` on macOS.
Fixes #36

Fix interface string on macOS

---

src/platform/macos_iokit/enumeration.rs
src/platform/windows_winusb/cfgmgr32.rs
src/platform/windows_winusb/enumeration.rs
src/platform/windows_winusb/hub.rs

https://github.com/kevinmehall/nusb/issues/38
These may not involve a device the app cares about, which results in noisy yet useless logs.

Lower log level to `debug!()` for errors in enumeration.

---

src/platform/windows_winusb/device.rs
src/platform/windows_winusb/enumeration.rs

This allows providing a better error message when failing to claim an interface, and may fix claiming a non-zero interface when a whole composite device is bound to WinUSB.

windows: Search for interface when claiming, not on device open

---

src/platform/linux_usbfs/usbfs.rs

The rustix `RawOpcode` type can vary depending on the target.
For example, targets that use the libc Linux configuration in rustix, the `RawOpcode` type is a type alias to `c_ulong` rather than `c_uint`.
I believe the `UsbFsIoctl` struct should remain the same in these configurations.
Discovered this while attempting to build for `s390x-unknown-linux-gnu`.
```
error[E0308]: mismatched types
--> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nusb-0.1.6/src/platform/linux_usbfs/usbfs.rs:78:25
|
78 |             ioctl_code: ioctl::NoneOpcode::<b'U', 23, ()>::OPCODE.raw(), // IOCTL_USBFS_CONNECT
|                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
```

Cast RawOpcode to the internal ioctl_code type (c_uint)

---

src/platform/macos_iokit/device.rs
src/platform/macos_iokit/iokit_usb.rs

The set of available endpoints can change when an interface's alt setting is changed, so on Mac we need to refresh our cached set of endpoints.
This necessitates wrapping the `BTreeMap` in a `Mutex` so it can be updated through the shared `self` reference in `set_alt_setting`.
I also changed `IoKitInterface::endpoints` to take a `&self` reference instead of `&mut self`. This seems sound from my inspection, but it should be reviewed carefully in case I missed something.

Mac: Update endpoints when interface alt setting is changed

---

src/platform/windows_winusb/device.rs
src/platform/windows_winusb/enumeration.rs
src/platform/windows_winusb/hub.rs

These were misdetected as high speed and Windows requires IOCTL_USB_GET_NODE_CONNECTION_INFORMATION_EX_V2 to detect them.
Based on #53, fixed to handle SuperSpeedPlus as well.

windows: Fix speed detection for SuperSpeed and SuperSpeed+

---

.github/workflows/rust.yml
Cargo.toml

Currently `nusb` does not specify a minimum supported Rust version (MSRV). This information would be useful to have.
In the process of trying to minimise the MSRV for a downstream project, I found that nusb's MSRV is currently 1.74.
This PR declares that MSRV, and updates CI to test with both the MSRV and the latest stable release, to give a warning if the minimum becomes inaccurate.
It might be possible to reduce the MSRV, if that's of interest.
During testing I found that older releases such as 0.1.3 could be built with Rust 1.64.
Use of [`Option::is_some_and`](https://doc.rust-lang.org/std/option/enum.Option.html#method.is_some_and) raised the requirement to 1.70.
Use of [`OsStr::as_encoded_bytes`](https://doc.rust-lang.org/std/ffi/os_str/struct.OsStr.html#method.as_encoded_bytes) …

Declare minimum supported rust version as 1.74, and test this in CI

---

src/platform/windows_winusb/transfer.rs

This result can be seen on Windows 10 while shutting down a bulk Queue (I was stopping capture in Packetry).
I believe it should be mapped to `TransferError::Cancelled`, and everything works as expected when I do so. This is also how it's [handled in libusb](https://github.com/libusb/libusb/blob/e678b3fad58a508cbd0a6e6dc777fb48346f948b/libusb/os/windows_common.c#L825-L831).
Since the error code was irreversibly mapped to `TransferError::Unknown`, it required patching nusb to find out what happened.
Perhaps `TransferError::Unknown` should have a field to retain an unexpected error code?

Handle `ERROR_OPERATION_ABORTED` result when a transfer is cancelled

---

src/enumeration.rs
src/platform/macos_iokit/enumeration.rs

When a value like locationID is over 0x80000000, it is still kCFNumberSInt32Type but becomes a negative number since CFNumber doesn't have unsigned types. This was rejected by `i64::try_into::<u32>()`. Use wrapping `as` instead of `try_into`.
Fixes https://github.com/kevinmehall/nusb/issues/66

macos: Fix enumeration of devices where bus number > 0x80

---

.github/workflows/rust.yml
Cargo.toml
src/platform/linux_usbfs/device.rs
src/platform/linux_usbfs/enumeration.rs
src/platform/linux_usbfs/events.rs
src/platform/linux_usbfs/hotplug.rs

Better logs for real errors, fewer unnecessary logs.
Includes a functional change of ignoring root hubs -- they're not useful to open, not exposed on other
platforms, and sometimes slow to read properties from for some reason.
Increases MSRV to 1.76 for `Result::inspect_err`

Clean up logs on Linux

---

src/enumeration.rs
src/platform/linux_usbfs/enumeration.rs
src/platform/macos_iokit/enumeration.rs
src/platform/windows_winusb/enumeration.rs

Not sure if this was not included intentionally or just missed. The bMaxPacketSize0 - packet size for endpoint zero that all devices must support - is included in the cached Device Descriptor on all platforms so seems sensible to include.

Add bMaxPacketSize0 to DeviceInfo

---

examples/descriptors.rs
examples/string_descriptors.rs
src/enumeration.rs
src/platform/linux_usbfs/device.rs
src/platform/linux_usbfs/enumeration.rs
src/platform/macos_iokit/enumeration.rs
src/platform/windows_winusb/enumeration.rs
src/platform/windows_winusb/util.rs

A simplified rewrite of @ccnut's https://github.com/kevinmehall/nusb/pull/58
```rs
/// Path of port numbers identifying the physical port where the device is
/// connected.
///
/// The first value is the bus number, and subsequent values represent the
/// port used on each hub on the path to this device. The path is expected
/// to remain stable across device insertions or reboots.
///
/// Since USB SuperSpeed is a separate topology from USB 2.0 speeds, a
/// physical port may be identified differently depending on speed.
pub fn port_chain(&self) -> Option<&[u8]>;
```
~~I've put the bus number at the beginning of the port chain, because the root hub port numbers are only unique within the bus. This makes it simpler to use as an identifier without getting the bus number separately. …

Add DeviceInfo::port_chain

---

src/lib.rs
src/platform/windows_winusb/enumeration.rs

I note there is [mention](https://github.com/kevinmehall/nusb/blob/main/src/lib.rs#L147) of this in the docs but is it intended or just the nature of only using `GUID_DEVINTERFACE_USB_DEVICE`? Since importing `GUID_DEVINTERFACE_USB_HUB` for the `list_buses`, I realise that non-root hubs can be obtained with this too in the `list_devices()`.
I believe it makes since to add it so hubs are included in the device list. If only because it makes Windows listing the same as the other platforms. I also think it makes sense as hub are devices and descriptors can be read, control messages used etc. unlike root hubs.

Windows: include hub devices in list like other platforms

---

src/platform/macos_iokit/device.rs
src/platform/macos_iokit/iokit.rs
src/platform/macos_iokit/mod.rs

Fixes #87 
`USBDeviceOpen` is not required for claiming interfaces. The documentation says it's required for control transfers, but it works without. It is, however, required for `set_configuration` and `reset`.
Having an interface claimed does not cause `set_configuration` and `reset` to fail on macOS like it does on Linux. After doing some testing, I ended up doing what libusb does and attempting to `USBDeviceOpen` when opening a device to try to get exclusive access, but ignoring failures, and trying again and requiring success only before `set_configuration` and `reset`. That's not perfect -- you can be the second process to open a device and fail  `USBDeviceOpen`, then the first process closes it, and a third process is then able to call these methods, but I can't find a better way.

macOS: Fix set_configuration and reset by using USBDeviceOpen

---

src/transfer/internal.rs

If `poll_completion_generic` runs between `notify_completion`'s `waker.take()` and `state.swap(STATE_COMPLETED, ...)`, it could see the transfer as pending and register its waker, but that waker would never be called.
This adds an Arc because once the transfer is set to `STATE_COMPLETED`, the other thread might free it, so we need to ensure the AtomicWaker stays alive while we use it. That's what the `take()` was intended to work around, but reading the waker before writing the status introduces the race.
Fixes #89

Fix race condition that could lose a transfer completion wakup

---

examples/descriptors.rs
examples/string_descriptors.rs
src/descriptors.rs
src/device.rs
src/platform/linux_usbfs/device.rs
src/platform/linux_usbfs/usbfs.rs
src/platform/macos_iokit/device.rs
src/platform/macos_iokit/enumeration.rs
src/platform/macos_iokit/iokit_usb.rs
src/platform/windows_winusb/device.rs

Hi! I'm doing some works on Termux. Termux provides a command `termux-usb` for accessing USB device. But it give me only a file descriptor, and I need to get some basic information about the device. So I did some works to get information about the device itself from opened device.
* fn `Device::get_device_descriptor()`
* ~fn `Device::get_device_info()`~
* struct `descriptors::DeviceDescriptor`
I'm sorry for the mistakes I made.
* Removed pub fn `device::Device::get_device_info`
* Removed pub fn `descriptors::DeviceDescriptor::speed`
* Removed fn `descriptors::DeviceDescriptor::format_usb_version`
* Removed fn `platform::linux_usbfs::device::LinuxDevice::get_busnum_and_devnum`
* Removed fn `enumeration::Speed::from_usb_version`
* Renamed fn …

Add support for getting device information from opened device on Linux

---

Cargo.toml
examples/blocking.rs
examples/bulk.rs
examples/buses.rs
examples/control.rs
examples/descriptors.rs
examples/detach.rs
examples/detach_claim.rs
examples/list.rs
examples/string_descriptors.rs
src/device.rs
src/enumeration.rs
src/ioaction.rs
src/lib.rs
src/maybe_future.rs
src/platform/linux_usbfs/device.rs
src/platform/linux_usbfs/enumeration.rs
src/platform/macos_iokit/device.rs
src/platform/macos_iokit/enumeration.rs
src/platform/windows_winusb/device.rs
src/platform/windows_winusb/enumeration.rs
src/transfer/queue.rs

`DeviceInfo::open`, `Device::from_fd`, `Device::set_configuration`, `Device::reset`, `Interface::set_alt_setting`, `Interface::clear_halt` all perform IO but are currently blocking because the underlying OS APIs are blocking.
`list_devices`,`list_buses`, `Device::claim_interface` `Device::detach_and_claim_interface` theoretically don't perform IO, but are also included here because they need to be async on WebUSB.
The `IoAction` trait allows defering these actions to the thread pool from the `blocking` crate when used asynchronously with `.await` / `IntoFuture`, or directly runs the blocking syscall synchronously with a `.wait()` method.
Open question: Should the dependency on `blocking` be behind a cargo feature, and if unset, should `IoAction` not impl `IntoFuture` or should it return a …

Make blocking APIs optionally async

---

src/descriptors.rs
src/device.rs
src/platform/linux_usbfs/device.rs
src/platform/windows_winusb/enumeration.rs

Freeing up the `Endpoint` name for the successor to `Queue`, while making the naming more consistent.

Descriptor API changes

---

src/enumeration.rs
src/platform/linux_usbfs/enumeration.rs
src/platform/macos_iokit/enumeration.rs
src/platform/windows_winusb/enumeration.rs

Added missing usb version (aka bcdUSB) to DeviceInfo. On Windows it is available in device descriptor directly. On linux it is in sysfs as version and it is parsed. On macOS it is available as bcdUSB property.
Tested on ubuntu 24.04, Windows 11 and macOS 15.3.1

Add usb version to device info

---

src/platform/macos_iokit/device.rs
src/platform/macos_iokit/enumeration.rs

Bug is exposed when a connected device has no continuous interface numbers. Then getting nth interface is different from getting interface of a specific number.
E.g. I have a device which has interfaces of numbers: 0, 1, 3, 4, 9. 
Number 2 is reserved for optional use (some variants of the device have this interface). Number 9 is for DFU interface. Space between 4 and 9 is for new functionalities.
Trying to claim interface 4 actually claimed interface 3, but I still was able to send control requests to interface 4. At the same time, another application (using libusb) has trouble to claim interface 3, because it has been already claimed by the first one using nusb.
This PR fixes this problem by getting and comparing `bInterfaceNumber` instead of using `nth` function on iterator.
logs from …

fix(macos): claiming incorrect interface

---

.github/workflows/rust.yml
Cargo.toml
src/lib.rs
src/maybe_future.rs

https://github.com/kevinmehall/nusb/pull/100 added a dependency on `blocking` for running blocking syscalls on a threadpool. This extends that to allow choosing `blocking` (`smol`) or `tokio` via cargo features, also allowing omitting both if the affected methods don't need to be used asynchronously.
This increases the MSRV to 1.79: The associated type bounds feature, stabilized in 1.79 allows adding an implied Send bound on all IntoFuture types used with MaybeFuture, so every function doesn't have to be marked as Send. This is going to be especially useful with wasm, because it allows the Send bound to be turned on and off in one place.

Add cargo features for `smol` and `tokio` runtimes

---

src/platform/macos_iokit/device.rs
src/platform/macos_iokit/enumeration.rs

Backport of #124
* fix(macos): claiming interface on macOS treats interface number as index
Bug is exposed when connected device has not continuous interface numbers. Then getting nth interface is not the same as getting interface of specific number.

[v0.1] fix(macos): claiming incorrect interface (#124)

---

src/descriptors.rs
src/device.rs
src/error.rs
src/lib.rs
src/platform/linux_usbfs/device.rs
src/platform/linux_usbfs/enumeration.rs
src/platform/linux_usbfs/events.rs
src/platform/linux_usbfs/hotplug.rs
src/platform/linux_usbfs/mod.rs
src/platform/macos_iokit/device.rs
src/platform/macos_iokit/enumeration.rs
src/platform/macos_iokit/hotplug.rs
src/platform/macos_iokit/iokit.rs
src/platform/macos_iokit/iokit_usb.rs
src/platform/macos_iokit/mod.rs
src/platform/windows_winusb/device.rs
src/platform/windows_winusb/enumeration.rs
src/platform/windows_winusb/events.rs
src/platform/windows_winusb/hotplug.rs
src/platform/windows_winusb/hub.rs
src/platform/windows_winusb/mod.rs
src/platform/windows_winusb/registry.rs
src/platform/windows_winusb/util.rs
src/transfer/mod.rs

The default mapping from OS error codes to io::Error's messages is often wrong
or misleading. We can do a lot better, but it takes a lot of error-handling code.

Define a new Error type instead of re-exporting std::io::Error

---

Cargo.toml
src/platform/macos_iokit/events.rs
src/platform/macos_iokit/iokit.rs
src/platform/macos_iokit/iokit_c.rs

IOUSBInterfaceInterface700 was added in macOS 10.10+ and IOUSBDeviceInterface650 in macOS 10.9+, both older than Rust's minimum of 10.12 so technically the breaking change was already broken by Rust, but might as well get this in on the nusb v0.2 semver bump because we'll want it later.

macOS: Update core-foundation, switch to IOUSBInterfaceInterface700 and IOUSBDeviceInterface650

---

Cargo.toml
src/platform/windows_winusb/cfgmgr32.rs
src/platform/windows_winusb/enumeration.rs
src/platform/windows_winusb/hotplug.rs

For usbccgp devices, nusb collected InterfaceInfo data from the properties of child device nodes, while for other devices it read and parsed the cached configuration descriptor. This changes to doing the latter for all devices, but still iterates usbccgp child nodes to populate cached interface strings when available.
This fixes InterfaceInfo missing interfaces below IADs (which do not have their own device nodes), and means that we should at least have class/subclass/protocol in hotplug events where Windows hasn't created the child device nodes yet (https://github.com/kevinmehall/nusb/issues/149).

windows: Always use interface descriptors rather than child device nodes for InterfaceInfo

---

src/enumeration.rs
src/lib.rs
src/platform/linux_usbfs/device.rs
src/platform/linux_usbfs/enumeration.rs
src/platform/linux_usbfs/mod.rs
src/platform/macos_iokit/enumeration.rs
src/platform/windows_winusb/enumeration.rs

Some fields are not available on those platforms, so this preemptively `cfg`s them out or removes them.
`list_devices` and `list_buses` may have worked on rooted Android, but this disables them for now so that JNI-based enumeration can be added without a breaking change. `Device::from_fd` currently supported for non-rooted Android remains available.

Future-proof v0.2 DeviceInfo and BusInfo for future Android and WebUSB backends
